CREATE TABLE InkTypes(
    ink_id INT PRIMARY KEY,
    name VARCHAR(64) UNIQUE NOT NULL,
    price INT NOT NULL
);
INSERT INTO InkTypes
VALUES(0, 'EPSON INK', 200);
INSERT INTO InkTypes
VALUES(1, 'EPSON PREMIUM INK', 300);
INSERT INTO InkTypes
VALUES(2, 'HP INK', 210);
INSERT INTO InkTypes
VALUES(3, 'HP PREMIUM INK', 320);
INSERT INTO InkTypes
VALUES(4, 'ECO SOLVENT INK', 800);
INSERT INTO InkTypes
VALUES(5, 'PHOTO BLACK INK', 950);
INSERT INTO InkTypes
VALUES(6, 'TOYO INK', 400);
INSERT INTO InkTypes
VALUES(7, 'MEGAMI INK', 200);
INSERT INTO InkTypes
VALUES(8, 'SAKATA INK', 210);
INSERT INTO InkTypes
VALUES(9, 'CANON INK', 250);